name: Test

on:
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
#          - windows-latest
        node: 
#          - 12.x
          - 14.x
          - 16.x
          - 18.x

    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Install npm@9
        run: npm i -g npm@9
      - name: Install modules - actor ${{ github.actor }} - version ${{ github.run_number }}
        run: npm ci
      - name: Run tests
        run: npm test
