name: Test

on:
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
#          - windows-latest
        node: 
#          - 12.x
          - 14.x
#          - 16.x

    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Install modules - actor ${{ github.actor }} - version ${{ github.run_number }}
        run: npm ci
      - name: Run tests
        run: npm test
